# Site Settings
title: Sneha Singh
description: "Finding beauty in turning data complexity into reliable actionable business insights."
url: "https://github.com/snehasingh44/snehasingh44.github.io"
baseurl: ""

# Theme Settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "air"

# Identity Sidebar
author:
  name   : "Sneha Singh"
  avatar : "/assets/images/profile.jpg"
  bio    : "Solution Consultant"
  location: "Dehradun, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sneha-singh-ss/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/snehasingh44"

# Build Settings
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

# Folders to include
include: ["_pages"]